### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by appsolut-jahn** [sarike/readable-bytes#4]
Compiling the project I get the warning: "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted" in file ./node_modules/readable-bytes/lib/index.js

Context:
- readable-bytes: ^2.0.1
- node: 12.18.1
- react app based on create-react-app

**Comment by sarike** [comment]
fixed at #3
